### ISSUE TITLE
代码和文章水平不在一个层次吧！！！😂

### ISSUE THREAD

**Issue by iamlijiu** [ouchuangxin/leave-sample#9]
看文章，写的头头是道的，结果代码拉下来，一言难尽，很难让人觉得这是同一个人的产出。
注释，包装类型，代码括号。既然，是一个教程我觉得还是写的规范一点好，我这拉下来P3C检测，夸夸的提示。

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！
